version: "3"

services:
  postgres:
    container_name: mussum_db
    image: "postgres:11.5"
    environment:
      - POSTGRES_USER:${DB_USERNAME}
      - POSTGRES_DB:${DB_NAME}
      - POSTGRES_PASSWORD:${DB_PASSWORD}
    expose:
      - "5432"
    ports:
      - ${DB_PORT}:${DB_PORT} 